apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c8nbe91mq-go 
  janus-idp.io/tekton: c8nbe91mq-go
  backstage.io/kubernetes-id: c8nbe91mq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c8nbe91mq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  