apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c8nbe91mq-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-38d1fb3ba4.w2j2.p3.openshiftapps.com/rhtap/rhtap-qe:acab02fcbbd6ab08ab4a4e374b31f73fe16e618f@sha256:b1aa52a82e70787a0d7c7eb116baeba433dbabfd687feddce49374e9f7103284
          name: container-image
